name: CI/CD for Roie Admin Flask app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubunutu-latest

    steps:
    - name: Checkout Repository
        uses: actions/checkout@v2
      
    - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        
    - name: Check if requirements.txt has changes
      id: check_requirements
      run: echo "::set-output name=changed::$(if [ -n "$(git diff --name-only ${{ github.event.before }}.. ${{ github.sha }} | grep 'requirements.txt')"]; then echo 'true'; else echo 'false'; fi)"

    - name: Install Dependencies
      if: steps.check_requirements.outpurs.changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER}}@${{ secrets.VULTR_SERVER_IP }} "cd /opt/roieadmin/ && python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt"

    - name: copy files to admin folder
      run: |
       rsync -a --exclude='credential.py' --exclude='*.dist' --exclude='myenv' -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }}" ./ ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }}:/opt/roieadmin/

    - name: Restart roieapp service
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart roieapp"

      - name: Restart Apache server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart apache2"