name: CI/CD for Roie Admin Flask app

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check if requirements.txt has changes
        id: check_requirements
        run: |
          git fetch
          git diff --name-only ${{ github.event.before }}..${{ github.sha }} > changed_files.txt
          cat changed_files.txt
          echo "changed=$(if grep -q 'requirements.txt' changed_files.txt; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

      - name: Install Dependencies
        if: env.changed == 'true'
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "cd /opt/admin_roie/ && python3 -m venv myenv && source myenv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"

      - name: copy files to admin folder
        run: |
          rsync -a --exclude='credentials.py' --exclude='*.dist' --exclude='myenv' -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }}" ./ ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }}:/opt/admin_roie/

      - name: Restart roieapp service
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart roieapp"

      - name: Restart Apache server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.VULTR_SSH_KEY }} ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart apache2"
