name: CI/CD for Roie Admin Flask app

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Unload SSH keys
        run: |
          eval $(ssh-agent -s)
          ssh-add -D

      - name: set up SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.VULTR_SSH_KEY }}
          known_hosts: ${{ secrets.VULTR_SSH_KNOWN_HOSTS }}

      - name: Check if requirements.txt has changes
        id: check_requirements
        run: |
          git fetch
          previous_commit=$(git log -1 --pretty=format:%H)
          git diff --name-only $previous_commit..${{ github.sha }} > changed_files.txt
          cat changed_files.txt
          echo "changed=$(if grep -q 'requirements.txt' changed_files.txt; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

      - name: Install Dependencies
        if: env.changed == 'true'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "cd /opt/admin_roie/ && python3 -m venv myenv && source myenv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"

      - name: Copy files to admin folder
        run: |
          rsync -a --exclude='credentials.py' --exclude='*.dist' --exclude='myenv' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }}:/opt/admin_roie/

      - name: Restart roieapp service
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart roieapp"

      - name: Restart Apache server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VULTR_SSH_USER }}@${{ secrets.VULTR_SERVER_IP }} "sudo systemctl restart apache2"
