name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULTR_SSH_KEY }}

      - name: Debug Private Key
        run: echo "$SSH_PRIVATE_KEY"

      - name: Create Directory on Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no root@45.32.179.99 "mkdir ~/githubFolder"
